apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: quay-config
  namespace: quay
spec:
  data:
    - remoteRef:
        key: secrets
        property: AWS_ACCESS_KEY
      secretKey: AWS_ACCESS_KEY
    - remoteRef:
        key: secrets
        property: s3_bucket_name
      secretKey: s3_bucket_name
    - remoteRef:
        key: app/secrets
        property: AWS_SECRET_ACCESS_KEY
      secretKey: AWS_SECRET_ACCESS_KEY
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: eso-secret-store
    namespace: openshift-gitops
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: quay-config
    template:
      engineVersion: v2
      mergePolicy: Replace
      templateFrom:
        - configMap:
            items:
              - key: config.yaml
                templateAs: Values
            name: quay-config-template
          target: Data
