apiVersion: v1
data:
  .git-credentials: aHR0cHM6Ly9zZm9yZW1hbi1yaDpnaXRodWJfcGF0XzExQU9OTTZFQTBSMjFDb1EzUk5hR29fQTdHa1B2enVkM0s5cVZwYzZadFJtYnB0THJDazR5bEZjQ0MyWDI3MUF0NFVVSUZDTEY2TWhPcm9VeVdAZ2l0aHViLmNvbS9zZm9yZW1hbi1yaC9yb3NhLWF1dG9tYXRpb24=
  .gitconfig: W2NyZWRlbnRpYWwgImh0dHBzOi8vZ2l0aHViLmNvbS9zZm9yZW1hbi1yaC9yb3NhLWF1dG9tYXRpb24iXQogIGhlbHBlciA9IHN0b3JlCg==
kind: Secret
metadata:
  name: github-creds
  namespace: python-sample
type: Opaque
